services:
  microservicio_tareas-fastapi-app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    container_name: microservicios_tareas
    networks:
      - microservicios_network_mv1

networks:
  microservicios_network_mv1:
    external: true







